
FROM jumidlej/raspios-buster:python3.7opencv4.1.2

USER root
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y libraspberrypi-bin
RUN apt-get install  libopenjp2-7

RUN apt-get install qt5-default
RUN apt-get install python3-pyqt5.qtquick python3-pyside2.qtquick python3-pyside2.qtquickwidgets qml-module-qtquick-controls2 qml-module-qtquick2
RUN apt-get upgrade -y


WORKDIR /home/pi/Desktop/vision_inspection/code/dir

ADD requirements.txt ./requirements.txt
RUN  python3 -m pip install  --upgrade pip
RUN  python3 -m pip install  -r requirements.txt 
