version: '3'
services:
  inspection_service:
    build: 
      dockerfile: DockerFile
      context: . 
    container_name: Vision_Inspection
    command: /bin/bash
    stdin_open: true
    #command: python3 ./video_converter.py 
    volumes:
      - /home/pi/Desktop/vision_inspection/code:/home/pi/Desktop/vision_inspection/code
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"
      - "/dev/mem:/dev:mem"
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
