version: '3'
services:
  inspection_service:
    build: 
      dockerfile: Dockerfile
      context: . 
    container_name: Vision_Inspection

    #command: python3 ./video_converter.py 
    volumes:
      - "home/pi:home/pi"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"