version: '3'
services:
  inspection_service:
    build: 
      dockerfile: Dockerfile
      #context: . 
    #image: markctm/vision_inspection_service
    container_name: Vision_Inspection2
    #command: /bin/bash
    stdin_open: true
    tty: true
    #restart: always
    #als
    #command: python3 /appsrc/gui.py   
    volumes:
      - /home/pi/Desktop/Vision_Inspection/code:/home/pi/Desktop/Vision_Inspection/code
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"
      - "/dev/mem:/dev:mem"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    command: python3 /home/pi/Desktop/Vision_Inspection/code/gui.py 
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    network_mode: "host"

